version: '3'

services:
  zeddring:
    build: .
    container_name: zeddring
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - ./data:/app/data
      - /var/run/dbus:/var/run/dbus
      - /var/run/bluetooth:/var/run/bluetooth
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bluetooth:/dev/bluetooth
      - /dev/input:/dev/input
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_ADMIN
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_APP=zeddring.web
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/var/run/dbus/system_bus_socket
      - SECRET_KEY=zeddring_secret_key_change_in_production
      - ZEDDRING_DB_PATH=/app/data/zeddring_data.sqlite
      - ZEDDRING_SCAN_INTERVAL=15
      - ZEDDRING_SCAN_TIMEOUT=10
      - ZEDDRING_MAX_RETRY_ATTEMPTS=3
      - ZEDDRING_RETRY_DELAY=300
      - ZEDDRING_WEB_HOST=0.0.0.0
      - ZEDDRING_WEB_PORT=5000
      - ZEDDRING_DEBUG=False
      - ZEDDRING_PERSISTENT_CONNECTION=True 