version: '3'

services:
  zeddring:
    build: .
    container_name: zeddring
    restart: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - ./data:/data
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/vcio:/dev/vcio"
      - "/dev/input/event0:/dev/input/event0"
    # Add capabilities for Bluetooth
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - ZEDDRING_DB_PATH=/data/zeddring_data.sqlite
      - ZEDDRING_SCAN_INTERVAL=60
      - ZEDDRING_SCAN_TIMEOUT=10
      - ZEDDRING_MAX_RETRY_ATTEMPTS=3
      - ZEDDRING_RETRY_DELAY=300
      - ZEDDRING_WEB_HOST=0.0.0.0
      - ZEDDRING_WEB_PORT=5000
      - ZEDDRING_DEBUG=False 